training_pipeline_config:
  pipeline_name: forestcover
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://github.com/ckunalgit/datasets/raw/main/covtype.zip
  raw_data_dir: raw_data
  zip_download_dir: zip_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html


